/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CounsellingRouteImport } from './routes/counselling'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as CareerSlugRouteImport } from './routes/career.$slug'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareComparisonRouteImport } from './routes/compare.$comparison'
import { Route as CompareUniversitiesRouteImport } from './routes/compare.universities'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseRouteImport } from './routes/courses.$course'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesSlugRouteImport } from './routes/universities.$slug'
import { Route as CompareCoursePairRouteImport } from './routes/compare.$course.$pair'
import { Route as CoursesCourseIndexRouteImport } from './routes/courses.$course.index'
import { Route as CoursesCourseSectionRouteImport } from './routes/courses.$course.$section'
import { Route as OnlineCoursesLevelCourseRouteImport } from './routes/online-courses.$level.$course'
import { Route as UniversitiesSlugIndexRouteImport } from './routes/universities.$slug.index'
import { Route as UniversitiesSlugAdmissionRouteImport } from './routes/universities.$slug.admission'
import { Route as UniversitiesSlugExaminationPatternRouteImport } from './routes/universities.$slug.examination-pattern'
import { Route as UniversitiesSlugPlacementRouteImport } from './routes/universities.$slug.placement'
import { Route as UniversitiesSlugScholarshipsRouteImport } from './routes/universities.$slug.scholarships'
import { Route as UniversitySlugCourseRouteImport } from './routes/university.$slug.$course'
import { Route as CoursesCourseSpecialisationSpecRouteImport } from './routes/courses.$course.specialisation.$spec'
import { Route as UniversitiesSlugCoursesCourseRouteImport } from './routes/universities.$slug.courses.$course'
import { Route as UniversitiesSlugCoursesCourseSectionRouteImport } from './routes/universities.$slug.courses.$course.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellingRoute = CounsellingRouteImport.update({
  id: '/counselling',
  path: '/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const CareerSlugRoute = CareerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareerRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const CompareComparisonRoute = CompareComparisonRouteImport.update({
  id: '/$comparison',
  path: '/$comparison',
  getParentRoute: () => CompareRoute,
} as any)
const CompareUniversitiesRoute = CompareUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => CompareRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseRoute = CoursesCourseRouteImport.update({
  id: '/$course',
  path: '/$course',
  getParentRoute: () => CoursesRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewsRoute,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversitiesRoute,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UniversitiesRoute,
} as any)
const CompareCoursePairRoute = CompareCoursePairRouteImport.update({
  id: '/$course/$pair',
  path: '/$course/$pair',
  getParentRoute: () => CompareRoute,
} as any)
const CoursesCourseIndexRoute = CoursesCourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseRoute,
} as any)
const CoursesCourseSectionRoute = CoursesCourseSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CoursesCourseRoute,
} as any)
const OnlineCoursesLevelCourseRoute =
  OnlineCoursesLevelCourseRouteImport.update({
    id: '/online-courses/$level/$course',
    path: '/online-courses/$level/$course',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesSlugIndexRoute = UniversitiesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversitiesSlugRoute,
} as any)
const UniversitiesSlugAdmissionRoute =
  UniversitiesSlugAdmissionRouteImport.update({
    id: '/admission',
    path: '/admission',
    getParentRoute: () => UniversitiesSlugRoute,
  } as any)
const UniversitiesSlugExaminationPatternRoute =
  UniversitiesSlugExaminationPatternRouteImport.update({
    id: '/examination-pattern',
    path: '/examination-pattern',
    getParentRoute: () => UniversitiesSlugRoute,
  } as any)
const UniversitiesSlugPlacementRoute =
  UniversitiesSlugPlacementRouteImport.update({
    id: '/placement',
    path: '/placement',
    getParentRoute: () => UniversitiesSlugRoute,
  } as any)
const UniversitiesSlugScholarshipsRoute =
  UniversitiesSlugScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => UniversitiesSlugRoute,
  } as any)
const UniversitySlugCourseRoute = UniversitySlugCourseRouteImport.update({
  id: '/university/$slug/$course',
  path: '/university/$slug/$course',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSpecialisationSpecRoute =
  CoursesCourseSpecialisationSpecRouteImport.update({
    id: '/specialisation/$spec',
    path: '/specialisation/$spec',
    getParentRoute: () => CoursesCourseRoute,
  } as any)
const UniversitiesSlugCoursesCourseRoute =
  UniversitiesSlugCoursesCourseRouteImport.update({
    id: '/courses/$course',
    path: '/courses/$course',
    getParentRoute: () => UniversitiesSlugRoute,
  } as any)
const UniversitiesSlugCoursesCourseSectionRoute =
  UniversitiesSlugCoursesCourseSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => UniversitiesSlugCoursesCourseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/universities': typeof UniversitiesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/career/$slug': typeof CareerSlugRoute
  '/compare/$comparison': typeof CompareComparisonRoute
  '/compare/universities': typeof CompareUniversitiesRoute
  '/courses/$course': typeof CoursesCourseRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRouteWithChildren
  '/blogs/': typeof BlogsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/compare/$course/$pair': typeof CompareCoursePairRoute
  '/courses/$course/$section': typeof CoursesCourseSectionRoute
  '/online-courses/$level/$course': typeof OnlineCoursesLevelCourseRoute
  '/universities/$slug/admission': typeof UniversitiesSlugAdmissionRoute
  '/universities/$slug/examination-pattern': typeof UniversitiesSlugExaminationPatternRoute
  '/universities/$slug/placement': typeof UniversitiesSlugPlacementRoute
  '/universities/$slug/scholarships': typeof UniversitiesSlugScholarshipsRoute
  '/university/$slug/$course': typeof UniversitySlugCourseRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/universities/$slug/': typeof UniversitiesSlugIndexRoute
  '/courses/$course/specialisation/$spec': typeof CoursesCourseSpecialisationSpecRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRouteWithChildren
  '/universities/$slug/courses/$course/$section': typeof UniversitiesSlugCoursesCourseSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/career': typeof CareerRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/career/$slug': typeof CareerSlugRoute
  '/compare/$comparison': typeof CompareComparisonRoute
  '/compare/universities': typeof CompareUniversitiesRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/compare': typeof CompareIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/news': typeof NewsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/compare/$course/$pair': typeof CompareCoursePairRoute
  '/courses/$course/$section': typeof CoursesCourseSectionRoute
  '/online-courses/$level/$course': typeof OnlineCoursesLevelCourseRoute
  '/universities/$slug/admission': typeof UniversitiesSlugAdmissionRoute
  '/universities/$slug/examination-pattern': typeof UniversitiesSlugExaminationPatternRoute
  '/universities/$slug/placement': typeof UniversitiesSlugPlacementRoute
  '/universities/$slug/scholarships': typeof UniversitiesSlugScholarshipsRoute
  '/university/$slug/$course': typeof UniversitySlugCourseRoute
  '/courses/$course': typeof CoursesCourseIndexRoute
  '/universities/$slug': typeof UniversitiesSlugIndexRoute
  '/courses/$course/specialisation/$spec': typeof CoursesCourseSpecialisationSpecRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRouteWithChildren
  '/universities/$slug/courses/$course/$section': typeof UniversitiesSlugCoursesCourseSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/universities': typeof UniversitiesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/career/$slug': typeof CareerSlugRoute
  '/compare/$comparison': typeof CompareComparisonRoute
  '/compare/universities': typeof CompareUniversitiesRoute
  '/courses/$course': typeof CoursesCourseRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRouteWithChildren
  '/blogs/': typeof BlogsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/compare/$course/$pair': typeof CompareCoursePairRoute
  '/courses/$course/$section': typeof CoursesCourseSectionRoute
  '/online-courses/$level/$course': typeof OnlineCoursesLevelCourseRoute
  '/universities/$slug/admission': typeof UniversitiesSlugAdmissionRoute
  '/universities/$slug/examination-pattern': typeof UniversitiesSlugExaminationPatternRoute
  '/universities/$slug/placement': typeof UniversitiesSlugPlacementRoute
  '/universities/$slug/scholarships': typeof UniversitiesSlugScholarshipsRoute
  '/university/$slug/$course': typeof UniversitySlugCourseRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/universities/$slug/': typeof UniversitiesSlugIndexRoute
  '/courses/$course/specialisation/$spec': typeof CoursesCourseSpecialisationSpecRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRouteWithChildren
  '/universities/$slug/courses/$course/$section': typeof UniversitiesSlugCoursesCourseSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/blogs'
    | '/career'
    | '/categories'
    | '/compare'
    | '/contact'
    | '/counselling'
    | '/courses'
    | '/news'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/tools'
    | '/universities'
    | '/blogs/$slug'
    | '/career/$slug'
    | '/compare/$comparison'
    | '/compare/universities'
    | '/courses/$course'
    | '/news/$slug'
    | '/reviews/$slug'
    | '/scholarships/$slug'
    | '/universities/$slug'
    | '/blogs/'
    | '/compare/'
    | '/courses/'
    | '/news/'
    | '/tools/'
    | '/universities/'
    | '/compare/$course/$pair'
    | '/courses/$course/$section'
    | '/online-courses/$level/$course'
    | '/universities/$slug/admission'
    | '/universities/$slug/examination-pattern'
    | '/universities/$slug/placement'
    | '/universities/$slug/scholarships'
    | '/university/$slug/$course'
    | '/courses/$course/'
    | '/universities/$slug/'
    | '/courses/$course/specialisation/$spec'
    | '/universities/$slug/courses/$course'
    | '/universities/$slug/courses/$course/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/career'
    | '/categories'
    | '/contact'
    | '/counselling'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/blogs/$slug'
    | '/career/$slug'
    | '/compare/$comparison'
    | '/compare/universities'
    | '/news/$slug'
    | '/reviews/$slug'
    | '/scholarships/$slug'
    | '/blogs'
    | '/compare'
    | '/courses'
    | '/news'
    | '/tools'
    | '/universities'
    | '/compare/$course/$pair'
    | '/courses/$course/$section'
    | '/online-courses/$level/$course'
    | '/universities/$slug/admission'
    | '/universities/$slug/examination-pattern'
    | '/universities/$slug/placement'
    | '/universities/$slug/scholarships'
    | '/university/$slug/$course'
    | '/courses/$course'
    | '/universities/$slug'
    | '/courses/$course/specialisation/$spec'
    | '/universities/$slug/courses/$course'
    | '/universities/$slug/courses/$course/$section'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/blogs'
    | '/career'
    | '/categories'
    | '/compare'
    | '/contact'
    | '/counselling'
    | '/courses'
    | '/news'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/tools'
    | '/universities'
    | '/blogs/$slug'
    | '/career/$slug'
    | '/compare/$comparison'
    | '/compare/universities'
    | '/courses/$course'
    | '/news/$slug'
    | '/reviews/$slug'
    | '/scholarships/$slug'
    | '/universities/$slug'
    | '/blogs/'
    | '/compare/'
    | '/courses/'
    | '/news/'
    | '/tools/'
    | '/universities/'
    | '/compare/$course/$pair'
    | '/courses/$course/$section'
    | '/online-courses/$level/$course'
    | '/universities/$slug/admission'
    | '/universities/$slug/examination-pattern'
    | '/universities/$slug/placement'
    | '/universities/$slug/scholarships'
    | '/university/$slug/$course'
    | '/courses/$course/'
    | '/universities/$slug/'
    | '/courses/$course/specialisation/$spec'
    | '/universities/$slug/courses/$course'
    | '/universities/$slug/courses/$course/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthorsRoute: typeof AuthorsRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CareerRoute: typeof CareerRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  CounsellingRoute: typeof CounsellingRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RankingsRoute: typeof RankingsRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  ScholarshipsRoute: typeof ScholarshipsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TagsRoute: typeof TagsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UniversitiesRoute: typeof UniversitiesRouteWithChildren
  OnlineCoursesLevelCourseRoute: typeof OnlineCoursesLevelCourseRoute
  UniversitySlugCourseRoute: typeof UniversitySlugCourseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselling': {
      id: '/counselling'
      path: '/counselling'
      fullPath: '/counselling'
      preLoaderRoute: typeof CounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/career/$slug': {
      id: '/career/$slug'
      path: '/$slug'
      fullPath: '/career/$slug'
      preLoaderRoute: typeof CareerSlugRouteImport
      parentRoute: typeof CareerRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/$comparison': {
      id: '/compare/$comparison'
      path: '/$comparison'
      fullPath: '/compare/$comparison'
      preLoaderRoute: typeof CompareComparisonRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/universities': {
      id: '/compare/universities'
      path: '/universities'
      fullPath: '/compare/universities'
      preLoaderRoute: typeof CompareUniversitiesRouteImport
      parentRoute: typeof CompareRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$course': {
      id: '/courses/$course'
      path: '/$course'
      fullPath: '/courses/$course'
      preLoaderRoute: typeof CoursesCourseRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/universities/': {
      id: '/universities/'
      path: '/'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/$slug': {
      id: '/universities/$slug'
      path: '/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/compare/$course/$pair': {
      id: '/compare/$course/$pair'
      path: '/$course/$pair'
      fullPath: '/compare/$course/$pair'
      preLoaderRoute: typeof CompareCoursePairRouteImport
      parentRoute: typeof CompareRoute
    }
    '/courses/$course/': {
      id: '/courses/$course/'
      path: '/'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof CoursesCourseIndexRouteImport
      parentRoute: typeof CoursesCourseRoute
    }
    '/courses/$course/$section': {
      id: '/courses/$course/$section'
      path: '/$section'
      fullPath: '/courses/$course/$section'
      preLoaderRoute: typeof CoursesCourseSectionRouteImport
      parentRoute: typeof CoursesCourseRoute
    }
    '/online-courses/$level/$course': {
      id: '/online-courses/$level/$course'
      path: '/online-courses/$level/$course'
      fullPath: '/online-courses/$level/$course'
      preLoaderRoute: typeof OnlineCoursesLevelCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$slug/': {
      id: '/universities/$slug/'
      path: '/'
      fullPath: '/universities/$slug/'
      preLoaderRoute: typeof UniversitiesSlugIndexRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/universities/$slug/admission': {
      id: '/universities/$slug/admission'
      path: '/admission'
      fullPath: '/universities/$slug/admission'
      preLoaderRoute: typeof UniversitiesSlugAdmissionRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/universities/$slug/examination-pattern': {
      id: '/universities/$slug/examination-pattern'
      path: '/examination-pattern'
      fullPath: '/universities/$slug/examination-pattern'
      preLoaderRoute: typeof UniversitiesSlugExaminationPatternRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/universities/$slug/placement': {
      id: '/universities/$slug/placement'
      path: '/placement'
      fullPath: '/universities/$slug/placement'
      preLoaderRoute: typeof UniversitiesSlugPlacementRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/universities/$slug/scholarships': {
      id: '/universities/$slug/scholarships'
      path: '/scholarships'
      fullPath: '/universities/$slug/scholarships'
      preLoaderRoute: typeof UniversitiesSlugScholarshipsRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/university/$slug/$course': {
      id: '/university/$slug/$course'
      path: '/university/$slug/$course'
      fullPath: '/university/$slug/$course'
      preLoaderRoute: typeof UniversitySlugCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/specialisation/$spec': {
      id: '/courses/$course/specialisation/$spec'
      path: '/specialisation/$spec'
      fullPath: '/courses/$course/specialisation/$spec'
      preLoaderRoute: typeof CoursesCourseSpecialisationSpecRouteImport
      parentRoute: typeof CoursesCourseRoute
    }
    '/universities/$slug/courses/$course': {
      id: '/universities/$slug/courses/$course'
      path: '/courses/$course'
      fullPath: '/universities/$slug/courses/$course'
      preLoaderRoute: typeof UniversitiesSlugCoursesCourseRouteImport
      parentRoute: typeof UniversitiesSlugRoute
    }
    '/universities/$slug/courses/$course/$section': {
      id: '/universities/$slug/courses/$course/$section'
      path: '/$section'
      fullPath: '/universities/$slug/courses/$course/$section'
      preLoaderRoute: typeof UniversitiesSlugCoursesCourseSectionRouteImport
      parentRoute: typeof UniversitiesSlugCoursesCourseRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface CareerRouteChildren {
  CareerSlugRoute: typeof CareerSlugRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerSlugRoute: CareerSlugRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface CompareRouteChildren {
  CompareComparisonRoute: typeof CompareComparisonRoute
  CompareUniversitiesRoute: typeof CompareUniversitiesRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CompareCoursePairRoute: typeof CompareCoursePairRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareComparisonRoute: CompareComparisonRoute,
  CompareUniversitiesRoute: CompareUniversitiesRoute,
  CompareIndexRoute: CompareIndexRoute,
  CompareCoursePairRoute: CompareCoursePairRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface CoursesCourseRouteChildren {
  CoursesCourseSectionRoute: typeof CoursesCourseSectionRoute
  CoursesCourseIndexRoute: typeof CoursesCourseIndexRoute
  CoursesCourseSpecialisationSpecRoute: typeof CoursesCourseSpecialisationSpecRoute
}

const CoursesCourseRouteChildren: CoursesCourseRouteChildren = {
  CoursesCourseSectionRoute: CoursesCourseSectionRoute,
  CoursesCourseIndexRoute: CoursesCourseIndexRoute,
  CoursesCourseSpecialisationSpecRoute: CoursesCourseSpecialisationSpecRoute,
}

const CoursesCourseRouteWithChildren = CoursesCourseRoute._addFileChildren(
  CoursesCourseRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseRoute: typeof CoursesCourseRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseRoute: CoursesCourseRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ReviewsRouteChildren {
  ReviewsSlugRoute: typeof ReviewsSlugRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsSlugRoute: ReviewsSlugRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

interface ScholarshipsRouteChildren {
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
}

const ScholarshipsRouteChildren: ScholarshipsRouteChildren = {
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
}

const ScholarshipsRouteWithChildren = ScholarshipsRoute._addFileChildren(
  ScholarshipsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface UniversitiesSlugCoursesCourseRouteChildren {
  UniversitiesSlugCoursesCourseSectionRoute: typeof UniversitiesSlugCoursesCourseSectionRoute
}

const UniversitiesSlugCoursesCourseRouteChildren: UniversitiesSlugCoursesCourseRouteChildren =
  {
    UniversitiesSlugCoursesCourseSectionRoute:
      UniversitiesSlugCoursesCourseSectionRoute,
  }

const UniversitiesSlugCoursesCourseRouteWithChildren =
  UniversitiesSlugCoursesCourseRoute._addFileChildren(
    UniversitiesSlugCoursesCourseRouteChildren,
  )

interface UniversitiesSlugRouteChildren {
  UniversitiesSlugAdmissionRoute: typeof UniversitiesSlugAdmissionRoute
  UniversitiesSlugExaminationPatternRoute: typeof UniversitiesSlugExaminationPatternRoute
  UniversitiesSlugPlacementRoute: typeof UniversitiesSlugPlacementRoute
  UniversitiesSlugScholarshipsRoute: typeof UniversitiesSlugScholarshipsRoute
  UniversitiesSlugIndexRoute: typeof UniversitiesSlugIndexRoute
  UniversitiesSlugCoursesCourseRoute: typeof UniversitiesSlugCoursesCourseRouteWithChildren
}

const UniversitiesSlugRouteChildren: UniversitiesSlugRouteChildren = {
  UniversitiesSlugAdmissionRoute: UniversitiesSlugAdmissionRoute,
  UniversitiesSlugExaminationPatternRoute:
    UniversitiesSlugExaminationPatternRoute,
  UniversitiesSlugPlacementRoute: UniversitiesSlugPlacementRoute,
  UniversitiesSlugScholarshipsRoute: UniversitiesSlugScholarshipsRoute,
  UniversitiesSlugIndexRoute: UniversitiesSlugIndexRoute,
  UniversitiesSlugCoursesCourseRoute:
    UniversitiesSlugCoursesCourseRouteWithChildren,
}

const UniversitiesSlugRouteWithChildren =
  UniversitiesSlugRoute._addFileChildren(UniversitiesSlugRouteChildren)

interface UniversitiesRouteChildren {
  UniversitiesSlugRoute: typeof UniversitiesSlugRouteWithChildren
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
}

const UniversitiesRouteChildren: UniversitiesRouteChildren = {
  UniversitiesSlugRoute: UniversitiesSlugRouteWithChildren,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
}

const UniversitiesRouteWithChildren = UniversitiesRoute._addFileChildren(
  UniversitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthorsRoute: AuthorsRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CareerRoute: CareerRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  CounsellingRoute: CounsellingRoute,
  CoursesRoute: CoursesRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RankingsRoute: RankingsRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  ScholarshipsRoute: ScholarshipsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TagsRoute: TagsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UniversitiesRoute: UniversitiesRouteWithChildren,
  OnlineCoursesLevelCourseRoute: OnlineCoursesLevelCourseRoute,
  UniversitySlugCourseRoute: UniversitySlugCourseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
